Update fetchers.R
ropensci/rix pull request #353
Opened 2024-10-25 07:52 UTC by jrosell

Related https://github.com/ropensci/rix/issues/352

2024-10-25 08:15 UTC, b-rodrigues requested changes
could you add a test for this use case?

2024-10-25 08:37 UTC, jrosell commented
It seems that fetchgit is working.

2024-10-28 10:06 UTC, b-rodrigues commented
Could we test with another package than uwu? I cannot get the environment to build even when adding `rustc` and `cargo` to the nativeBuildInputs. The functionality seems to be fine, but I would like test if the environment is buildable.

2024-10-28 10:20 UTC, b-rodrigues commented
Perhaps with poorman, it has no depends
https://github.com/nathaneastwood/poorman

2024-10-28 12:53 UTC, jrosell commented
I created a new small and dependency free package called {helloworld}. It's in path to CRAN too.

2024-10-28 18:58 UTC, b-rodrigues approved these changes
LGTM

@philipp-baumann what do you think?

2024-10-31 09:20 UTC, philipp-baumann requested changes

2024-10-31 09:20 UTC, philipp-baumann commented on tests/testthat/test-fetchers.R
> +      list(package_name = "helloworld", repo_url = "https://github.com/jrosell/helloworld/", commit = "48ceefdfb4858743454ede71d19999c2e6b38ed2")
```suggestion
      list(
        package_name = "helloworld",
        repo_url = "https://github.com/jrosell/helloworld/",
        commit = "48ceefdfb4858743454ede71d19999c2e6b38ed2"
      )
```

2024-10-31 10:59 UTC, philipp-baumann commented
@jrosell thanks for the fix. @b-rodrigues @jrosell I think we need to do something with the intersect logic, I think we might have `LinkingTo` but no Depends and Imports, where we set to `character(0)` and might not work.

2024-10-31 14:51 UTC, b-rodrigues commented
I think it's working as intended I just tried using the DESCRIPTION file from RcppEigen which only has a LinkingTo RCPP: https://github.com/RcppCore/RcppEigen/blob/master/DESCRIPTION

but this made me realize we should be testing `get_imports()` as well using some different DESCRIPTION files. @jrosell  let me know if you wish to add these tests, if not I can take a stab at it.

2024-10-31 15:59 UTC, jrosell commented
Please, proceed as you prefer. I assume my PR is safer than the current main and you could merge and add tests afterwards, but it's up to you. I only made this PR for a current bug I was experiencing, but I guess more tests would be required in the long term.

2024-10-31 16:05 UTC, philipp-baumann commented
> Please, proceed as you prefer. I assume my PR is safer than the current main and you could merge and add tests afterwards, but it's up to you. I only made this PR for a current bug I was experiencing, but I guess more tests would be required in the long term.

```r
library("devtools")
library("data.table")

pkgs_bh_links <- revdep(
  "BH",
  dependencies = c("LinkingTo"),
  recursive = FALSE,
  ignore = NULL,
  bioconductor = FALSE
)

# alpine linux
db <- tools::CRAN_package_db()
setDT(db)

db_noinput <-
  db[!is.na(`Reverse linking to`) & is.na(Depends) & is.na(Imports), ]

db_noinput$Package

pr_353_nloptr <- file.path(".", "pr_353", "nloptr")

rix(
  r_ver = "latest",
  git_pkgs = list(
    list(
      package_name = "https://github.com/astamm/nloptr",
      repo_url = "https://github.com/astamm/nloptr",
      commit = "6d4943aff5a47bd3b3914f86acaa5d6eeeccaa77"
    )
  ),
  project_path = pr_353_nloptr,
  overwrite = TRUE
)

nix_build(project_path = pr_353_nloptr)


pr_353_bh <- file.path(".", "pr_353", "bh")

rix(
  r_ver = "latest",
  git_pkgs = list(
    list(
      package_name = "BH",
      repo_url = "https://github.com/eddelbuettel/bh",
      commit = "3d8adc434004d0b219aa4f508dbe8c3ddc2d916b"
    )
  ),
  project_path = pr_353_bh,
  overwrite = TRUE
)

```

2024-10-31 22:29 UTC, philipp-baumann commented
It's good to have a fix, so having a solid solution in a few days that covers all cases for a fix is more sustainable in my opinion, especially for proper versioning and particularly for a package where reproducibility is key, hence trust in solid dev.

2024-11-08 15:20 UTC, jrosell commented
> > Please, proceed as you prefer. I assume my PR is safer than the current main and you could merge and add tests afterwards, but it's up to you. I only made this PR for a current bug I was experiencing, but I guess more tests would be required in the long term.
> 
> ```r
> library("rix")
> 
> pr_353 <- file.path("./pr_353")
> 
> rix(
>   r_ver = "latest",
>   r_pkgs = c("devtools", "styler", "lintr", "desc", "data.table"),
>   git_pkgs = list(
>     list(
>       package_name = "rix",
>       repo_url = "https://github.com/ropensci/rix",
>       commit = "26825ecdc890b0b91842404656ea52be6b831f51"
>     )
>   ),
>   project_path = pr_353,
>   overwrite = TRUE
> )
> 
> nix_build(project_path = pr_353)
> 
> ```
> 
> ```r
> library("devtools")
> library("data.table")
> 
> pkgs_bh_links <- revdep(
>   "BH",
>   dependencies = c("LinkingTo"),
>   recursive = FALSE,
>   ignore = NULL,
>   bioconductor = FALSE
> )
> 
> # alpine linux
> db <- tools::CRAN_package_db()
> setDT(db)
> 
> db_noinput <-
>   db[!is.na(`Reverse linking to`) & is.na(Depends) & is.na(Imports), ]
> 
> db_noinput$Package
> 
> pr_353_nloptr <- file.path(".", "pr_353", "nloptr")
> 
> rix(
>   r_ver = "latest",
>   git_pkgs = list(
>     list(
>       package_name = "https://github.com/astamm/nloptr",
>       repo_url = "https://github.com/astamm/nloptr",
>       commit = "6d4943aff5a47bd3b3914f86acaa5d6eeeccaa77"
>     )
>   ),
>   project_path = pr_353_nloptr,
>   overwrite = TRUE
> )
> 
> nix_build(project_path = pr_353_nloptr)
> 
> 
> pr_353_bh <- file.path(".", "pr_353", "bh")
> 
> rix(
>   r_ver = "latest",
>   git_pkgs = list(
>     list(
>       package_name = "BH",
>       repo_url = "https://github.com/eddelbuettel/bh",
>       commit = "3d8adc434004d0b219aa4f508dbe8c3ddc2d916b"
>     )
>   ),
>   project_path = pr_353_bh,
>   overwrite = TRUE
> )
> 
> ```
> 
> 

What is the expected output of all these? I could add them to my PR.

2024-11-20 14:36 UTC, b-rodrigues commented
as discussed on matrix, we’re merging as this is functional

2024-11-20 14:37 UTC, merged